ci: remove pre-release workflow from create-prerelease.yml
* Eliminated the pre-release job from the workflow, as the intention is to manage pre-releases directly through GitHub tagging instead.

diff --git a/.github/workflows/create-prerelease.yml b/.github/workflows/create-prerelease.yml
--- a/.github/workflows/create-prerelease.yml
+++ b/.github/workflows/create-prerelease.yml
@@ -293,45 +293,46 @@ jobs:
           name: asvec-artifacts
           path: asvec-*
           overwrite: true
-
-  pre-release:
-    needs:
-      - sign
-      - build
-    runs-on: ubuntu-latest
-    steps:
-      - name: 'Git checkout'
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: 'Download Artifacts'
-        uses: actions/download-artifact@v4
-        with:
-          name: asvec-artifacts
-      - name: 'Create a new pre-release'
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          set -e
-          TAG=${{needs.build.outputs.version}}
-          FULLCOMMIT=$(git rev-parse HEAD)
-          gh release create -R github.com/aerospike/asvec --prerelease --target ${FULLCOMMIT} --title "Asvec - ${TAG}" ${TAG} ${{needs.build.outputs.artifacts}} ${{needs.build.outputs.sha-artifacts}} ${{needs.build.outputs.asc-artifacts}}
-      - name: 'Delete previous pre-release'
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          DELPREV: ${{ inputs.deletePrevBuild }}
-        run: |
-          if [ "${DELPREV}" = "true" ]; then
-            set -e
-            gh release list -R github.com/aerospike/asvec -L 100 | grep Pre-release | awk -F'\t' '{print $3}' | while read -r line; do
-            if [ "$line" != "${{needs.build.outputs.version}}" ]; then
-              if [[ "$line" == "${{ inputs.version }}-SNAPSHOT-"* ]]; then
-              echo "Removing $line"
-              gh release delete "$line" -R github.com/aerospike/asvec --yes --cleanup-tag
-              fi
-            fi
-            done
-          fi
+# Should remove the pre-release workflow. Pre-release should be done by making the appropriate pre release on github or tagging.
+# that is the idea anyway
+#   pre-release:
+#     needs:
+#       - sign
+#       - build
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: 'Git checkout'
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 0
+#       - name: 'Download Artifacts'
+#         uses: actions/download-artifact@v4
+#         with:
+#           name: asvec-artifacts
+#       - name: 'Create a new pre-release'
+#         env:
+#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#         run: |
+#           set -e
+#           TAG=${{needs.build.outputs.version}}
+#           FULLCOMMIT=$(git rev-parse HEAD)
+#           gh release create -R github.com/aerospike/asvec --prerelease --target ${FULLCOMMIT} --title "Asvec - ${TAG}" ${TAG} ${{needs.build.outputs.artifacts}} ${{needs.build.outputs.sha-artifacts}} ${{needs.build.outputs.asc-artifacts}}
+#       - name: 'Delete previous pre-release'
+#         env:
+#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#           DELPREV: ${{ inputs.deletePrevBuild }}
+#         run: |
+#           if [ "${DELPREV}" = "true" ]; then
+#             set -e
+#             gh release list -R github.com/aerospike/asvec -L 100 | grep Pre-release | awk -F'\t' '{print $3}' | while read -r line; do
+#             if [ "$line" != "${{needs.build.outputs.version}}" ]; then
+#               if [[ "$line" == "${{ inputs.version }}-SNAPSHOT-"* ]]; then
+#               echo "Removing $line"
+#               gh release delete "$line" -R github.com/aerospike/asvec --yes --cleanup-tag
+#               fi
+#             fi
+#             done
+#           fi
   build-docker:
     needs:
       - sign
